### ISSUE TITLE
vite config 报错，不支持 import

### ISSUE THREAD

**Issue by JackFGreen** [Summer-andy/vite-plugin-transform-css-modules#1]
vite: 2.3.0

![image](https://user-images.githubusercontent.com/23187848/121293800-d1bda280-c91e-11eb-922c-db2c3d3d08db.png)

**Comment by kwzm** [comment]
同样的问题

**Comment by duanbaosheng** [comment]
the same  error  as above  同样的问题+1

**Comment by Summer-andy** [comment]
大佬们  vite库修复了开发和打包环境一致性问题，之前我也提了一个issue [https://github.com/vitejs/vite/issues/3255#issuecomment-848415454](url), 这个方案应该不行了，我最近太忙啦 没有时间研究啦 不好意思各位大佬 ～

**Comment by Summer-andy** [comment]
后面 我在这个项目用 其他方式实现css module  [https://github.com/Summer-andy/vite-react-template](https://github.com/Summer-andy/vite-react-template) 通过前置插件和后置插件来实现css module

**Comment by JackFGreen** [comment]
> 后面 我在这个项目用 其他方式实现css module https://github.com/Summer-andy/vite-react-template 通过前置插件和后置插件来实现css module

大佬，我用源码引入倒是可以了，但是没有hmr，我看这个项目的plugin2有hmr的代码，是可以用了吗

**Comment by arleyGuoLei** [comment]
the same error as above 同样的问题+1

**Comment by zjjjjjjjjjjd** [comment]
那咋办啊，vite的官方说因为你这个可以实现，他们又不想给用户太多配置，所以把这个rp关掉了，结果这边又不行了:(

**Comment by JackFGreen** [comment]
写了个插件，有需要的可以自己引入项目试一下
https://github.com/JackFGreen/vite-plugin-normal-css-to-module

**Comment by zjjjjjjjjjjd** [comment]
> 写了个插件，有需要的可以自己引入项目试一下 https://github.com/JackFGreen/vite-plugin-normal-css-to-module

感谢大佬，拿过来改了一下能用，已star
